name: TestChimp Test Runner
description: 'Enhanced TestChimp GitHub Action with AI-powered test repair and configurable success criteria'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  api-key:
    description: 'TestChimp project API key (required for CI/CD authentication)'
    required: true
  
  project-id:
    description: 'TestChimp project ID (required for CI/CD authentication)'
    required: true
  
  testchimp-endpoint:
    description: 'TestChimp API endpoint (optional)'
    required: false
    default: 'https://featureservice.testchimp.io'
  
  test-type:
    description: 'Type of test to run (FS_TEST for API tests, UI_TEST for UI tests)'
    required: true
  
  test-case-regex:
    description: 'Regex pattern to filter test cases (optional)'
    required: false
    default: '.*'
  
  test-suite-regex:
    description: 'Regex pattern to filter test suites (optional)'
    required: false
    default: '.*'
  
  test-directory:
    description: 'Directory containing test files (relative to repository root). For monorepos, use comma-separated directories (e.g., "ui/tests,api/tests")'
    required: false
    default: 'tests'
  
  log-level:
    description: 'Log output level (all, failures, none)'
    required: false
    default: 'all'
  
  success-criteria:
    description: 'Test success criteria (ORIGINAL_SUCCESS or REPAIR_SUCCESS_WITH_CONFIDENCE)'
    required: false
    default: 'ORIGINAL_SUCCESS'
  
  repair-confidence-threshold:
    description: 'Minimum confidence score required for repair success (1-5)'
    required: false
    default: '4'
  
  create-pr-on-repair:
    description: 'Create a pull request with repaired test files (true/false)'
    required: false
    default: 'false'
  
  pr-title:
    description: 'Title for the pull request (optional)'
    required: false
    default: 'TestChimp: AI-repaired test files'
  
  pr-body:
    description: 'Body for the pull request (optional)'
    required: false
    default: 'This PR contains test files that were automatically repaired by TestChimp AI.'
  
  headless:
    description: 'Run browser in headless mode (automatically forced to true in GitHub Actions)'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['playwright'].version)")" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run TestChimp Action
      id: testchimp
      run: |
        # Pass all GitHub Actions environment variables to ts-node
        export GITHUB_ACTIONS=true
        export GITHUB_WORKFLOW="${{ github.workflow }}"
        export GITHUB_REPOSITORY="${{ github.repository }}"
        export GITHUB_REF="${{ github.ref }}"
        export GITHUB_SHA="${{ github.sha }}"
        export GITHUB_HEAD_REF="${{ github.head_ref }}"
        export GITHUB_BASE_REF="${{ github.base_ref }}"
        export GITHUB_EVENT_NAME="${{ github.event_name }}"
        export GITHUB_WORKSPACE="${{ github.workspace }}"
        export GITHUB_ACTION_PATH="${{ github.action_path }}"
        
        # Pass all input variables
        export INPUT_API_KEY="${{ inputs.api-key }}"
        export INPUT_PROJECT_ID="${{ inputs.project-id }}"
        export INPUT_TESTCHIMP_ENDPOINT="${{ inputs.testchimp-endpoint }}"
        export INPUT_TEST_TYPE="${{ inputs.test-type }}"
        export INPUT_TEST_CASE_REGEX="${{ inputs.test-case-regex }}"
        export INPUT_TEST_SUITE_REGEX="${{ inputs.test-suite-regex }}"
        export INPUT_TEST_DIRECTORY="${{ inputs.test-directory }}"
        export INPUT_RECURSIVE="${{ inputs.recursive }}"
        export INPUT_INCLUDE_PATTERN="${{ inputs.include-pattern }}"
        export INPUT_EXCLUDE_PATTERN="${{ inputs.exclude-pattern }}"
        export INPUT_MODE="${{ inputs.mode }}"
        export INPUT_DEFLAKE_RUNS="${{ inputs.deflake-runs }}"
        export INPUT_HEADLESS="${{ inputs.headless }}"
        export INPUT_SUCCESS_CRITERIA="${{ inputs.success-criteria }}"
        export INPUT_REPAIR_CONFIDENCE_THRESHOLD="${{ inputs.repair-confidence-threshold }}"
        export INPUT_CREATE_PR_ON_REPAIR="${{ inputs.create-pr-on-repair }}"
        export INPUT_PR_TITLE="${{ inputs.pr-title }}"
        export INPUT_PR_BODY="${{ inputs.pr-body }}"
        
        # Pass environment variables
        export TESTCHIMP_ENV="${{ env.TESTCHIMP_ENV }}"
        export NODE_ENV="${{ env.NODE_ENV }}"
        
        # Change to repository directory for git operations
        cd ${{ github.workspace }}
        
        # Run the action and set outputs
        npx ts-node ${{ github.action_path }}/src/index.ts
        
        # Set outputs from JSON file
        if [ -f "testchimp-outputs.json" ]; then
          STATUS=$(jq -r '.status' testchimp-outputs.json)
          TEST_COUNT=$(jq -r '.testCount' testchimp-outputs.json)
          SUCCESS_COUNT=$(jq -r '.successCount' testchimp-outputs.json)
          FAILURE_COUNT=$(jq -r '.failureCount' testchimp-outputs.json)
          REPAIRED_COUNT=$(jq -r '.repairedCount' testchimp-outputs.json)
          REPAIRED_ABOVE_THRESHOLD=$(jq -r '.repairedAboveThreshold' testchimp-outputs.json)
          REPAIRED_BELOW_THRESHOLD=$(jq -r '.repairedBelowThreshold' testchimp-outputs.json)
          SUCCESS_CRITERIA_USED=$(jq -r '.successCriteriaUsed' testchimp-outputs.json)
          
          echo "status=${STATUS}" >> $GITHUB_OUTPUT
          echo "test-count=${TEST_COUNT}" >> $GITHUB_OUTPUT
          echo "success-count=${SUCCESS_COUNT}" >> $GITHUB_OUTPUT
          echo "failure-count=${FAILURE_COUNT}" >> $GITHUB_OUTPUT
          echo "repaired-count=${REPAIRED_COUNT}" >> $GITHUB_OUTPUT
          echo "repaired-above-threshold=${REPAIRED_ABOVE_THRESHOLD}" >> $GITHUB_OUTPUT
          echo "repaired-below-threshold=${REPAIRED_BELOW_THRESHOLD}" >> $GITHUB_OUTPUT
          echo "success-criteria-used=${SUCCESS_CRITERIA_USED}" >> $GITHUB_OUTPUT
        fi
      shell: bash
outputs:
  status:
    description: 'Overall execution status'
    value: ${{ steps.testchimp.outputs.status }}
  test-count:
    description: 'Number of tests executed'
    value: ${{ steps.testchimp.outputs.test-count }}
  success-count:
    description: 'Number of successful tests'
    value: ${{ steps.testchimp.outputs.success-count }}
  failure-count:
    description: 'Number of failed tests'
    value: ${{ steps.testchimp.outputs.failure-count }}
  repaired-count:
    description: 'Number of tests that were repaired'
    value: ${{ steps.testchimp.outputs.repaired-count }}
  repaired-above-threshold:
    description: 'Number of tests repaired with confidence above threshold'
    value: ${{ steps.testchimp.outputs.repaired-above-threshold }}
  repaired-below-threshold:
    description: 'Number of tests repaired with confidence below threshold'
    value: ${{ steps.testchimp.outputs.repaired-below-threshold }}
  success-criteria-used:
    description: 'Success criteria that was applied (ORIGINAL_SUCCESS or REPAIR_SUCCESS_WITH_CONFIDENCE)'
    value: ${{ steps.testchimp.outputs.success-criteria-used }}
