name: TestChimp Test Runner
description: 'Enhanced TestChimp GitHub Action with AI-powered test repair and configurable success criteria'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  api-key:
    description: 'TestChimp project API key (required for CI/CD authentication)'
    required: true
  
  project-id:
    description: 'TestChimp project ID (required for CI/CD authentication)'
    required: true
  
  testchimp-endpoint:
    description: 'TestChimp API endpoint (optional)'
    required: false
    default: 'https://featureservice.testchimp.io'
  
  test-type:
    description: 'Type of test to run (FS_TEST for API tests, UI_TEST for UI tests)'
    required: true
  
  test-case-regex:
    description: 'Regex pattern to filter test cases (optional)'
    required: false
    default: '.*'
  
  test-suite-regex:
    description: 'Regex pattern to filter test suites (optional)'
    required: false
    default: '.*'
  
  log-level:
    description: 'Log output level (all, failures, none)'
    required: false
    default: 'all'
  
  success-criteria:
    description: 'Test success criteria (ORIGINAL_SUCCESS or REPAIR_SUCCESS_WITH_CONFIDENCE)'
    required: false
    default: 'ORIGINAL_SUCCESS'
  
  repair-confidence-threshold:
    description: 'Minimum confidence score required for repair success (1-5)'
    required: false
    default: '4'
  
  create-pr-on-repair:
    description: 'Create a pull request with repaired test files (true/false)'
    required: false
    default: 'false'
  
  pr-title:
    description: 'Title for the pull request (optional)'
    required: false
    default: 'TestChimp: AI-repaired test files'
  
  pr-body:
    description: 'Body for the pull request (optional)'
    required: false
    default: 'This PR contains test files that were automatically repaired by TestChimp AI.'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run TestChimp Action
      run: npx ts-node src/index.ts
      shell: bash
      working-directory: ${{ github.action_path }}
outputs:
  status:
    description: 'Overall execution status'
  test-count:
    description: 'Number of tests executed'
  success-count:
    description: 'Number of successful tests'
  failure-count:
    description: 'Number of failed tests'
  repaired-count:
    description: 'Number of tests that were repaired'
  repaired-above-threshold:
    description: 'Number of tests repaired with confidence above threshold'
  repaired-below-threshold:
    description: 'Number of tests repaired with confidence below threshold'
  success-criteria-used:
    description: 'Success criteria that was applied (ORIGINAL_SUCCESS or REPAIR_SUCCESS_WITH_CONFIDENCE)'
